name = "Herring Cove"
description = "Julie Golzarian is a software engineer and the founder of LiteItForward"
license = "MIT"
tags = ["liteitforward.azurewebsites.net/", "LiteItForward.com"]
min_version = 0.20

[author]
    name = "Julie Golzarian"
    homepage = "http://spf13.com"

# If Porting existing theme
[original]
    author =  "arnp"
    repo = "http://www.github.com/arnp/herring-cove"
